### ISSUE TITLE
WES Moka - Variant comments page quirk?

### ISSUE THREAD

**Issue by SueLillis** [moka-guys/helpdesk#165]
Hello,
The recent changes to the variants comments page in WES Moka have had another unforeseen side effect. 
When the variant box is full of lots of information, when then typing something at the bottom of the page, the page jumps back to the top. Therefore, it is not possible to view what you are typing as you type it. 
Might be easier to explain this one in person! 
Thanks
Sue

**Comment by AmyAmelia** [comment]
More information: Issue is with the comment box on the form with the AGCS comment box. User is unable to view what is being typed if the amount of text exceeds the screen size as the form focuses on the top of the text box as soon as an edit is made.

**Comment by AmyAmelia** [comment]
Issue was due to the size of the text box in relation to the size of the computer screen. This form layout has been edited and this fix will be issued in the next Moka release. 
Additional point: The ACMG classification summary should be entered in the 'AGMG rule invoked' box for ease rather than within the variant comment box.
