### ISSUE TITLE
URGENT: Array requests dropping off runsheets list when patient status is changed from "Array"

### ISSUE THREAD

**Issue by CharlotteLee1** [moka-guys/helpdesk#177]
Is there any way to have both NGS and array requests progressing simultaneously in Moka?

2 instances where NGS and arrays have both been requested to be performed urgently and simultaneously. In once instance the patient status was changed from "Array" to "NGS", causing the sample to no longer appear on the runsheet list. This caused a delay as the paperwork sat in the blackbox until it was identified in an audit. In the other instance the status was "NGS" and had to be changed to "Array" during Moka booking on, which may cause the sample to disappear from the NGS/WES list.

**Comment by woook** [comment]
Have investigated and turns out the patient wasn't lost. The paperwork was investigated because of the NGS status (which is unusual) but the patient was being processed correctly. They hadn't had an array yet because they were a general referral (not rush) and so were just in the queue.

For reference, once an array request is entered into Moka, the patient status has no effect on whether the array progresses or not.
