### ISSUE TITLE
Retrieve list of in-house panels from Moka

### ISSUE THREAD

**Issue by SueLillis** [moka-guys/helpdesk#241]
Clinic would like us to create a list of all in-house panels in Moka, with details of the genes on each of these panels.

Please can one of the bioinformaticians export all of the panels under 'panel type 1'  ?

Could this be saved as an excel somewhere? 
Happy to provide more information, if required. 

Many thanks
Sue

**Comment by andyb3** [comment]
Hi Sue,

Do you know what they want this for?

Thanks,
Andy

**Comment by SueLillis** [comment]
Hi Andy,

The clinic would like to be able to view what genes are on each of our inhouse panels without having to order a WES request in Moka.
Ideally, the would like to view this in Moka, however we appreciate that this would cause some extra work for you.  We’ve decided that a dump of all panels will be good enough for now.

Let me know if you need any further info.
Thanks
Sue

**Comment by aledj2** [comment]
Hi Sue,
Please see attached spreadsheet @ S:\Genetics_Data2\Array\Audits and Projects\180731_inhouse_panels
Thanks,
Aled

**Comment by SueLillis** [comment]
Dear Aled,
Thank you very much for this.   Quick question – is this the only output Moka can do?

If the answer is yes that’s fine. We can easily ask someone to go through this to create a more useable document for the clinicians (i.e. each panel in a separate column rather than all in one).

Thought it was worth checking with you first.

Thanks
Sue

**Comment by aledj2** [comment]
Hi Sue,

To be honest creating a nicer/more complex output is going to be very low on our priority list.

The panel column can be filtered in Excel.

Thanks,

Aled
On 31/07/18 12:27, SueLillis wrote:
Dear Aled,
Thank you very much for this. Quick question – is this the only output Moka can do?

If the answer is yes that’s fine. We can easily ask someone to go through this to create a more useable document for the clinicians (i.e. each panel in a separate column rather than all in one).

Thought it was worth checking with you first.

Thanks
Sue

**Comment by SueLillis** [comment]
That’s fine Aled, totally understand!
