### ISSUE TITLE
Impact Assessment: NHSmail spoofing changes

### ISSUE THREAD

**Issue by andyb3** [moka-guys/helpdesk#259]
https://binfx.slack.com/files/U0AG77G01/FC4EMFS3C/spoofingcontrolsonthenhsmailservice.pdf

**Comment by aledj2** [comment]
Graeme producing preliminary list of things to change.
Can use NHS spoofing server

**Comment by Graeme-Smith** [comment]
Need to replace a couple of lines of code in:
moka-guys/benchmarking_tool – upload.html
moka-guys/benchmarking_tool – config file
woook/automate_demultiplex – automate_demultiplex_config.py

**Comment by Graeme-Smith** [comment]
Wook to look at Amazon AWS settings - verify the email address moka.alerts@gstt.nhs.uk as belonging to us.

**Comment by andyb3** [comment]
Andy to find code that sends message to moka alerts nhs.net

**Comment by NMNS93** [comment]
Graeme to change config for benchmarking and automated demultiplex, then submit for code review.

**Comment by aledj2** [comment]
benchmarking tool is done
? in process of testing automated demultiplexing script - probably not too urgent as emails are still coming through
One email did not come through because it went to the mokaguys junk folder so was not forwarded. The emails were whitelisted so should be forwarded as previous. Not sure what will happen when all emails are blocked (new year?).

**Comment by andyb3** [comment]
Will do a release on automate_demultiplexing

**Comment by andyb3** [comment]
Roll out along with Sention and MultiQC updates

**Comment by aledj2** [comment]
rolled out today
