### ISSUE TITLE
WES - no sex entered for patient in Moka

### ISSUE THREAD

**Issue by hkuoppamaa** [moka-guys/helpdesk#72]
Hi,

PRU 431334:01 (NGS test ID 819) doesn't have sex entered in Moka. Could this be remedied please?

Thanks,
Heidi

**Comment by woook** [comment]
If Ms Heidi could enter the sex for this patient in Geneworks, that would be a remedy.

Thank you most kindly, 

Wook

**Comment by hkuoppamaa** [comment]
Haha, thank you Mr Wook. Didn't realise it would be that simple. So is it only the old cases we need to bother you with?

**Comment by woook** [comment]
As far as I know, sex in Moka is taken directly from Geneworks and so this should be a remedy for all similar cases (there could be other issues though of course). Hyvää päivää.

**Comment by hkuoppamaa** [comment]
Ah, ok. Got confused as we just had a WES meeting and I was told we need to contact bioinfo if sex is missing. I'll let the WES team know. 안녕히 계세요

**Comment by woook** [comment]
Ah I think that is for sex in the filename as all should now have M/F/U in the filename (so that the pipeline can perform sex checking). Or it might be if the automated sex check says that it's not as expected. We're still calibrating and so are expecting (and have had) a few false positives. But more importantly, there are a number of reasons for a sex check alert (e.g. mosaic Turner's) and so we've asked people to let us know when this occurs. Toivottavasti on järkevää. Hyvää iltapäivää suomalainen nainen.
