### ISSUE TITLE
WES - unable to generate/find coverage report

### ISSUE THREAD

**Issue by hkuoppamaa** [moka-guys/helpdesk#80]
When I try to generate a coverage report for NGS test ID 811 (PRU 410465:01) Moka tells me it can be found in P:\DNA LAB\Current\WES\Coverage reports. However, it doesn't seem to be there. I can't see it in P:\DNA LAB\R&D\New Tests\WES\Results\Coverage reports either. Help, please.

**Comment by AmyAmelia** [comment]
Hi Hedi, This is an issue regrading moving the coverage report generated from a holding area to the final location. This has been fixed in the lasted version of Moka. Unfortunately at the present time we are unable to roll out this version to remote workers. For the time being when you create a coverage report, can you raise a github request we will move the file for you. 
I have moved this report for you.
Amy
